{
    'name': 'egp_procurement',
    'version': '1.1.0',
    'summary': 'Procurement Management System',
    'sequence': -100,
    'category': 'Procurement',
    'depends': ['mail', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/pmis_menu.xml',
        'data/pmis_project_sequence.xml',
        'data/procurement_category_data.xml',
        'wizard/pmis_cash_report_wizard.xml',
        'wizard/pmis_vendor_report_wizard.xml',
        'wizard/pmis_purchoon_purchase_report_wizard.xml',
        'wizard/pmis_plan_report_wizard.xml',
        'wizard/pmis_projects_report_wizard.xml',
        'wizard/pmis_bidded_projects_report_wizard.xml',

        'report/pmis_purchase_report_templates.xml',
        'report/pmis_purchase_report.xml',
        'report/pmis_cash_report.xml',
        'report/pmis_vendor_report.xml',
        'report/pmis_purchoon_purchase_report.xml',
        'report/pmis_plan_report.xml',
        'report/pmis_plan_template_report.xml',
        'report/pmis_project_report_views.xml',
        'report/pmis_offer_opening_report.xml',
        'report/pmis_projects_report.xml',
        "views/purchoon_purchase/pmis_cash_reception.xml",
        "views/purchoon_purchase/pmis_cash_refund.xml",
        "views/purchoon_purchase/pmis_purchase_kharidari.xml",
        'views/purchoon_purchase/pmis_purchase_project.xml',
        'views/purchoon_purchase/pmis_purchase_qoutation_line.xml',
        'views/purchoon_purchase/pmis_purchase_qoutation.xml',
        'views/vendors/address.xml',
        'views/vendors/pmis_vendors.xml',
        'views/vendors/pmis_vendor_block.xml',
        "views/vendors/pmis_vendor_agent.xml",
        'views/procurement_projects/pmis_projects.xml',
        'views/procurement_projects/pmis_construction_project.xml',
        # # 'views/procurement_projects/pmis_procurement.xml',
        'views/procurement_plan/pmis_project_plan.xml',
        'views/procurement_plan/pmis_plan_template.xml',
        'views/pmis_bank.xml',
        'views/project_announcment_view.xml',
        'views/pmis_offer_submission_view.xml',
        'views/pmis_offer_ghoshai.xml',
        'views/pmis_basic_evaluation_view.xml',
        'views/pmis_basic_evaluation_checkbox_view.xml',
        'views/pmis_offers_details_view.xml',
        "views/pmis_offer_details_info_view.xml",
        "views/pmis_offer's_evaluations_view.xml",
        'views/pmis_contract_agreement_view.xml',
        'views/pmis_guarante_view.xml',
        'views/pmis_offer_acceptance_view.xml',
        'views/pmis_offer_evaluation_view.xml',
        'views/pmis_bidding_winner_view.xml',
        'views/pmis_contract_management_view.xml',
        'views/pmis_delivery_description_view.xml',
        "views/pmis_payment_view.xml",
        "views/pmis_m7_view.xml",
        "views/pmis_winner_selection.xml",
        "views/pmis_m_cv_work_job_announcment.xml",
        "views/pmis_m_first_shortless_view.xml",
        "views/pmis_m_candidate_view.xml",
        "views/pmis_m_offerghishai_view.xml",
        "views/pmis_m_basic_evaluation_view.xml",
        "views/pmis_m_consult_offerghoshai_view.xml",
        "views/pmis_m_consult_offerghoshai_view.xml",
        "views/pmis_m_evaluation_view.xml",
        "views/pmis_m_interview_view.xml",
        "views/pmis_m_consult_interviw_view.xml",
        "views/pmis_m_consult_evaluation_project_view.xml",
        "views/pmis_m_test_announcement_view.xml",
        "views/pmis_m_winner_candidates_view.xml",
        "views/project_m_announcment_view.xml",
        "views/pmis_m_first_shortlist_candidates_view.xml",
        "views/pmis_bidding_winning_announcement_views.xml",

    ],
    'assets': {
        'web.assets_frontend': [
            'static/src/css/style.css',

        ],
    },
    # 'assets': {
    #         'web.assets_backend': [
    #             '/pms_real_estate/static/src/css/pmsCss.scss', 'web.assets_frontend':
    # ]},

    'demo': [],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',

}
